apiVersion: batch/v1
kind: Job
metadata:
  name: google-photos-backup-initdb
  namespace: google-photos-backup
spec:
  backoffLimit: 0
  template:
    spec:
      volumes:
      - name: photostore
        persistentVolumeClaim:
          claimName: google-photos-backup-db-store
      restartPolicy: Never
      containers:
      - name: google-photos-backup
        image: gammons1/google_photos_backup:latest
        volumeMounts:
        - name: photostore
          mountPath: "/app/db/"
        imagePullPolicy: Always
        env:
          - name: PUSHGATEWAY_URL
            value: "http://prometheus-pushgateway.prometheus.svc.cluster.local:9091"

          - name: HANDLER
            value: "S3"

          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: gpb
                key: google-client-id
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: gpb
                key: google-client-secret

          - name: REFRESH_TOKEN
            valueFrom:
              secretKeyRef:
                name: gpb
                key: refresh-token

          - name: AWS_REGION
            value: "us-east-2"
          - name: S3_BUCKET
            value: "gammons-google-photos-archive"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: gpb
                key: aws-access-key-id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: gpb
                key: aws-secret-access-key
        command: ["bundle","exec","rake","process"]
