apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: google-photos-backup-db-store
  namespace: google-photos-backup
  # annotations:
  #   volume.beta.kubernetes.io/storage-class: "nfs-client"
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
